<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Simulasi</name>
   <tag></tag>
   <elementGuidId>110e03f6-4cbd-4700-93d5-251fa79b4cc5</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Page not found - Sahabat Pegadaian  Solusi Gadai Terbaik - Tips Menabung Emas - Inspirasi Investasi Terbaik/a_Simulasi.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-7311']/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Page not found - Sahabat Pegadaian  Solusi Gadai Terbaik - Tips Menabung Emas - Inspirasi Investasi Terbaik/a_Simulasi.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-7311 > a.sf-with-ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83f3c66d-ce23-4a36-bc76-ffa4867fea0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sf-with-ul</value>
      <webElementGuid>583ec63a-178e-4653-80b1-999d6dcc717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simulasi</value>
      <webElementGuid>6c9f30c4-30dc-4103-a929-489723a5647b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js no-applicationcache geolocation history postmessage svg websockets localstorage sessionstorage websqldatabase webworkers hashchange audio canvas canvastext video webgl cssgradients multiplebgs opacity rgba inlinesvg hsla supports svgclippaths smil fontface generatedcontent textshadow cssanimations backgroundsize borderimage borderradius csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside boxshadow flexbox cssreflections csstransforms csstransforms3d csstransitions js_active  vc_desktop  vc_transform  vc_transform  indexeddb indexeddb-deletedatabase&quot;]/body[@class=&quot;error404 wp-embed-responsive jeg_toggle_light jnews jsc_normal wpb-js-composer js-comp-ver-6.9.0 vc_responsive&quot;]/div[@class=&quot;jeg_viewport&quot;]/div[@class=&quot;jeg_header_wrapper&quot;]/div[@class=&quot;jeg_header normal&quot;]/div[@class=&quot;jeg_midbar jeg_container normal&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;jeg_nav_row&quot;]/div[@class=&quot;jeg_nav_col jeg_nav_right jeg_nav_normal&quot;]/div[@class=&quot;item_wrap jeg_nav_alignright&quot;]/div[@class=&quot;jeg_nav_item jeg_main_menu_wrapper&quot;]/div[@class=&quot;jeg_mainmenu_wrap&quot;]/ul[@class=&quot;jeg_menu jeg_main_menu jeg_menu_style_5 sf-js-enabled sf-arrows&quot;]/li[@id=&quot;menu-item-7311&quot;]/a[@class=&quot;sf-with-ul&quot;]</value>
      <webElementGuid>5aee33b6-be29-47c6-b288-41376f147076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-7311']/a</value>
      <webElementGuid>64d82cb0-60e4-42b4-a982-b49fea885b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Simulasi')]</value>
      <webElementGuid>7f30c1a2-0a15-4920-b320-96f822074b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acara'])[1]/following::a[1]</value>
      <webElementGuid>616e037c-9a48-40b2-856f-411f7f93e463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wirausaha'])[1]/following::a[2]</value>
      <webElementGuid>c006cdad-f526-4bf3-8681-cf061645e04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Emas Batangan'])[1]/preceding::a[1]</value>
      <webElementGuid>1cb177a1-6337-42f8-b026-f84da1a88bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simulasi Tabungan Emas'])[1]/preceding::a[2]</value>
      <webElementGuid>824698ed-6a52-4b70-be01-b4a24dbfa28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simulasi']/parent::*</value>
      <webElementGuid>511e7a28-c628-41ea-a387-646a64a50b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>23f07d62-affa-4222-bebc-fe0c7893a091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Simulasi' or . = 'Simulasi')]</value>
      <webElementGuid>f1a266c6-5404-4d3e-bc28-48b0a7a31935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
