<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_selesai</name>
   <tag></tag>
   <elementGuidId>136e7c85-5d0a-479d-b96e-0059a828a562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;btn-selesai-pdf-simulasi&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5d79fdb8-cbcd-44fb-b985-66df56bd9188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-selesai-pdf-simulasi&quot;)</value>
      <webElementGuid>5a17eb96-4042-4ecc-8a4b-e21ffc29052b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
