<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>display_total_uang_muka</name>
   <tag></tag>
   <elementGuidId>880bc53d-6d2f-4ad9-be7f-832a2dae7de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#display_total_uang_muka</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='display_total_uang_muka']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4abdbf0b-3594-45de-ae03-50d6de374f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nominal-hasil</value>
      <webElementGuid>b364d35c-3391-42c0-942f-81dcf7c9254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_total_uang_muka</value>
      <webElementGuid>ce710c69-609c-4404-8df9-9e6b8c32c15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 0</value>
      <webElementGuid>a17bdd37-c686-47b8-a26f-9154f106dc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_total_uang_muka&quot;)</value>
      <webElementGuid>b8450d6e-be0f-43ad-b8cc-81828b929cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='display_total_uang_muka']</value>
      <webElementGuid>7bb40085-74eb-4877-a80a-5f289aeb89cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simulasi-segment-total-uang-muka']/p</value>
      <webElementGuid>587644e2-cdff-485b-a4a1-5920da488ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkiraan Maksimal Uang Pinjaman'])[1]/following::p[1]</value>
      <webElementGuid>2ef5db73-db81-4b3c-a31d-0f2ee4332c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jaminan Anda belum mencukupi.'])[1]/following::p[1]</value>
      <webElementGuid>1a5dd58e-a6cf-48e4-9454-1cf9114aebe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian'])[1]/preceding::p[1]</value>
      <webElementGuid>07bb7483-5816-4f19-be0b-ffe8370e3008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan Sekarang'])[1]/preceding::p[3]</value>
      <webElementGuid>f25681a3-5d36-45ba-b5ba-72b3f7f0f671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp 0']/parent::*</value>
      <webElementGuid>24db1871-a10d-49e1-ad42-80c7b7f8c0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>b8b845e3-2219-49e1-ab76-dbf4589cb2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'display_total_uang_muka' and (text() = 'Rp 0' or . = 'Rp 0')]</value>
      <webElementGuid>28a65d6f-586f-42ff-9502-d01fa259a2aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
