<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Terima Kasih</name>
   <tag></tag>
   <elementGuidId>0469c75b-bddc-4293-9241-c6b21c484e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.succes-tittle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-thank-you']/div/div[2]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>a663d9f3-6077-4660-9461-85b154f15dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>succes-tittle</value>
      <webElementGuid>3eb9bca8-59d8-48c3-9510-138cf6b50184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terima Kasih</value>
      <webElementGuid>9a91b101-4ea1-47cf-a995-b29b45a4da29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-thank-you&quot;)/div[@class=&quot;modal-content&quot;]/div[2]/h4[@class=&quot;succes-tittle&quot;]</value>
      <webElementGuid>64e1cdbc-d33f-4d42-8121-daf140e7fdac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-thank-you']/div/div[2]/h4</value>
      <webElementGuid>877c141d-c8c8-44cd-8fa9-276151f6cb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::h4[1]</value>
      <webElementGuid>e58667ef-1cbe-49d8-8ee8-97ddc4c2682c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Simulasi'])[3]/following::h4[1]</value>
      <webElementGuid>42bd5a03-d7cd-4921-b8b4-ad922134887e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[1]/preceding::h4[1]</value>
      <webElementGuid>5652ea6d-b27d-4dfb-9ad8-87bbb6b36887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::h4[1]</value>
      <webElementGuid>4693e120-f62d-4912-a6f1-f0e26a036e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terima Kasih']/parent::*</value>
      <webElementGuid>04f282f8-1119-4f56-84ef-510294140ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4</value>
      <webElementGuid>08973a28-76e2-4b86-9537-72e4a6ed5ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Terima Kasih' or . = 'Terima Kasih')]</value>
      <webElementGuid>94bbc96f-1f81-40b6-8efe-49007c518a4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
