<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Tambah Jaminan</name>
   <tag></tag>
   <elementGuidId>52f79298-4410-4a97-a7a8-67c67a4397b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='dialog-jaminan-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialog-jaminan-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>9ed4681f-0093-44d8-97a4-31fbb9d90a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>98b42a46-d241-4733-b536-7501612070e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialog-jaminan-title</value>
      <webElementGuid>566d88ac-3c27-4008-86ac-0863072044d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Jaminan</value>
      <webElementGuid>79bedb6b-4726-4bc5-99d6-c78bc4a74591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-jaminan-title&quot;)</value>
      <webElementGuid>dd02a7f0-6b45-4de7-9c2e-ea5a3509e403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='dialog-jaminan-title']</value>
      <webElementGuid>ed8f3266-7dfe-443d-af27-10334e0dbe02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mymodaltambahjaminan']/div/div/div/h5</value>
      <webElementGuid>7d546c22-b13b-4307-80fb-ca6c6e781082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi via Pegadaian Digital'])[1]/following::h5[1]</value>
      <webElementGuid>79a2f186-d0c4-4a63-861b-fb853a53a151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Simulasi'])[1]/following::h5[1]</value>
      <webElementGuid>cf3e15ee-3d67-43fe-b818-70391ac6c331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::h5[1]</value>
      <webElementGuid>f7598028-8341-4683-b7cb-f0d0c9ec761f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Emas'])[1]/preceding::h5[1]</value>
      <webElementGuid>6ee8f596-77fa-41ab-9ba7-dd2095694b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>8d5e7414-efbc-4a27-bf30-b1c3823b4dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'dialog-jaminan-title' and (text() = 'Tambah Jaminan' or . = 'Tambah Jaminan')]</value>
      <webElementGuid>c88c18e1-9373-4f70-9ec9-1eb4aec8de6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
