<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gram_berat_perhiasan</name>
   <tag></tag>
   <elementGuidId>3d66b035-561f-41ee-9e06-2d46b2722a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#berat_perhiasan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='berat_perhiasan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>454fc7f2-244b-45c2-81fd-aaf7d77a462c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan gram</value>
      <webElementGuid>9fe710c5-3e02-4818-9866-f4eeadce6d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>218feccc-64b7-4546-9f13-248fd84c1a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>berat_perhiasan</value>
      <webElementGuid>edc3d5a4-53ab-44a2-81c0-de707d274202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-decimal</value>
      <webElementGuid>b76f1ba9-07d2-4bc9-92e0-b7b4d5eac455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;berat_perhiasan&quot;)</value>
      <webElementGuid>12ba6483-dc3f-4ecb-893b-bf90636874e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='berat_perhiasan']</value>
      <webElementGuid>baa26e6c-471b-4c19-bd82-c37e6fc70329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perhiasan-form-group']/div[3]/div/input</value>
      <webElementGuid>e47b03f5-c880-4f40-8657-fa7779242751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>7e782258-8892-43cc-8c12-65889df7b283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan gram' and @type = 'text' and @id = 'berat_perhiasan']</value>
      <webElementGuid>c58a66a6-684e-4b87-acd0-bbf14b2d3216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
