<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kadar</name>
   <tag></tag>
   <elementGuidId>ee23ac8a-b36b-4700-9adb-9e8749645444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='perhiasan-form-group']/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>42e12fb3-7428-4dec-8590-ca3e3acc3102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>kadar</value>
      <webElementGuid>999e32cb-7b43-4162-a099-25db0ec80ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kadar</value>
      <webElementGuid>9fa6f20e-2f94-43e9-9b5c-d6b48fdd47db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perhiasan-form-group&quot;)/div[@class=&quot;form-group&quot;]/label[1]</value>
      <webElementGuid>3e3d105a-0dcb-4bac-a907-4548cc7848d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perhiasan-form-group']/div[2]/label</value>
      <webElementGuid>691180f4-b0c5-41f3-b952-c01caed134e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jenis Perhiasan'])[2]/following::label[1]</value>
      <webElementGuid>30cca51d-910a-4973-a3c2-e1b65e81da12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Perhiasan'])[1]/following::label[1]</value>
      <webElementGuid>9366a046-0bcd-4713-92d4-d51411163094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kadar'])[2]/preceding::label[1]</value>
      <webElementGuid>9c9b281b-e172-4dbc-a2a9-e2e4b0bfe352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat Tanpa Mata'])[1]/preceding::label[1]</value>
      <webElementGuid>4f7a8da7-3c7f-4673-9a7f-381efd8825f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kadar']/parent::*</value>
      <webElementGuid>9b39d01b-7cb6-4b80-8a3f-17068a21ce8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>5e5cc5b2-51f6-493b-8b64-85321b31e18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Kadar' or . = 'Kadar')]</value>
      <webElementGuid>52bcda07-3496-4dde-94df-eeb3f9d5352a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
