<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Jenis Perhiasan</name>
   <tag></tag>
   <elementGuidId>996cf61d-138a-4531-a406-97b596e50ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='perhiasan-form-group']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#perhiasan-form-group > div.form-group > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7c90b222-f634-49da-8a96-41ac57a1959c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>jenis-perhiasan</value>
      <webElementGuid>95db875c-7ef6-472d-80a2-979386a8d37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jenis Perhiasan</value>
      <webElementGuid>f6c6cd31-351a-428f-bb93-d7786509ba9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perhiasan-form-group&quot;)/div[@class=&quot;form-group&quot;]/label[1]</value>
      <webElementGuid>0b3596f3-08f6-4f46-a560-f474aabbd31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perhiasan-form-group']/div/label</value>
      <webElementGuid>883133c6-144b-4a47-9c13-28d68000c71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhiasan'])[2]/following::label[1]</value>
      <webElementGuid>92fc13f6-9a2a-48f7-bc20-2e46df568c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Emas'])[1]/following::label[1]</value>
      <webElementGuid>1cee834b-7cdd-4881-acbe-866aeb2bab99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jenis Perhiasan'])[2]/preceding::label[1]</value>
      <webElementGuid>115ee8da-a335-4806-8b3f-e33d978391d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kadar'])[1]/preceding::label[1]</value>
      <webElementGuid>a58ed225-e987-4a99-97d6-73843a481a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jenis Perhiasan']/parent::*</value>
      <webElementGuid>87b82b56-f579-4ee9-8669-b3754aa9bf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>369c72bd-7ac1-49ae-b1e6-034f5473569f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Jenis Perhiasan' or . = 'Jenis Perhiasan')]</value>
      <webElementGuid>4e61fe76-0de8-4d05-8c62-6120a998eeaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
