<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rp 810.000</name>
   <tag></tag>
   <elementGuidId>1c4036df-de1e-4111-a2e2-e0916a863c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#display_total_uang_muka</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='display_total_uang_muka']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d3d50fc8-4880-4ff6-b822-3b99212c0c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nominal-hasil</value>
      <webElementGuid>e0e4b2b1-3366-41ab-aa0b-f62cec29affb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_total_uang_muka</value>
      <webElementGuid>ff38c3e4-170b-4095-92a2-d387688bd58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 810.000</value>
      <webElementGuid>d2b257ed-fbbf-4d71-8e21-1a8b9df254d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_total_uang_muka&quot;)</value>
      <webElementGuid>f9c78ae1-06b7-4257-8a89-15b4e9320f98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='display_total_uang_muka']</value>
      <webElementGuid>a6ce7fe3-5bb3-4cb8-907f-24893c320240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simulasi-segment-total-uang-muka']/p</value>
      <webElementGuid>43cd2cc0-fa2a-4373-ad37-c067fef2d7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkiraan Maksimal Uang Pinjaman'])[1]/following::p[1]</value>
      <webElementGuid>a5dc28ca-6aa6-4b0f-a9ab-c6a38bf3725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jaminan Anda belum mencukupi.'])[1]/following::p[1]</value>
      <webElementGuid>bf0e803f-c0ec-4bff-8144-c0e1278cb408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian'])[1]/preceding::p[1]</value>
      <webElementGuid>13b9dd27-1851-4684-b9d0-93103a2f8fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan Sekarang'])[1]/preceding::p[3]</value>
      <webElementGuid>52b7a843-dccb-41e9-a870-66410decb64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp 810.000']/parent::*</value>
      <webElementGuid>41bc44c4-10bc-461d-9da5-8b14a07f18ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>ad974dfb-d095-4c44-91eb-8affd7b6aa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'display_total_uang_muka' and (text() = 'Rp 810.000' or . = 'Rp 810.000')]</value>
      <webElementGuid>292ee026-6a86-4ea5-ac87-04d9e4af635e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
