<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rp 0</name>
   <tag></tag>
   <elementGuidId>ac3ecafa-2d00-4788-a235-de1e491fd007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#display_total_uang_muka</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='display_total_uang_muka']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>90c32283-c3bb-4321-8892-61e0625c41d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nominal-hasil</value>
      <webElementGuid>a4413265-7150-454e-86b6-a84ed49417ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_total_uang_muka</value>
      <webElementGuid>f7f45a39-8a9e-49c6-8ad4-1568103c3d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 0</value>
      <webElementGuid>6ae70a3e-140a-4257-8aeb-11972642dfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_total_uang_muka&quot;)</value>
      <webElementGuid>e2caf3b7-9c82-4e44-b64e-d4ef6efb10dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='display_total_uang_muka']</value>
      <webElementGuid>b4a3477a-0eb4-4e86-9e9d-4b3728a0be4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simulasi-segment-total-uang-muka']/p</value>
      <webElementGuid>b9dc33ac-91f2-43bb-8a8c-13b127e35aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkiraan Maksimal Uang Pinjaman'])[1]/following::p[1]</value>
      <webElementGuid>f5daa2c4-360e-4d0b-a463-772bc184ad74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jaminan Anda belum mencukupi.'])[1]/following::p[1]</value>
      <webElementGuid>a24a69b6-4a7d-4282-9a8b-a305671036af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian'])[1]/preceding::p[1]</value>
      <webElementGuid>80701cf7-6d2c-45bf-85c8-294aeab23256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan Sekarang'])[1]/preceding::p[3]</value>
      <webElementGuid>f44ae993-e8ad-4eda-bb59-dfaa77aee793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp 0']/parent::*</value>
      <webElementGuid>f3eaba73-0f5f-4663-8bf4-f4c6db86112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>3e5bc17d-c3c7-41df-a696-6cc742b05d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'display_total_uang_muka' and (text() = 'Rp 0' or . = 'Rp 0')]</value>
      <webElementGuid>2c719406-c916-4100-8443-9aa4a96e0cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
