<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih cincin</name>
   <tag></tag>
   <elementGuidId>5767341c-af16-42e7-b5a0-9d1f8c849fbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class=&quot;select2-results&quot;]//li[normalize-space()=&quot;Cincin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>92c4ac8c-d4ad-4b32-80e0-12ac21682594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678967230881</value>
      <webElementGuid>4039f661-d458-45c8-908a-67971deec0e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
