<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih 24 karat</name>
   <tag></tag>
   <elementGuidId>bd0f2327-5f8e-457f-aaa0-9d6e59e92375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-kadar-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class=&quot;select2-results&quot;]//li[normalize-space()=&quot;24 Karat&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38aecf8f-15b2-4cde-ad64-04b16164759d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>34b34a12-f9af-4f4d-9ce7-f932b252c1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-kadar-container</value>
      <webElementGuid>6be5d01d-e190-442e-939c-0367b66f8678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3fa53e92-ae41-4894-a149-a2c500db25d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ef2674a-ae98-4003-9fe8-d4a3c0beedb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Kadar</value>
      <webElementGuid>a7d860e3-9d58-462c-9c9f-73083bc49c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kadar</value>
      <webElementGuid>a61e9c78-8f30-4e7d-80a0-46a9ea4b0351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-kadar-container&quot;)</value>
      <webElementGuid>f677b6fa-5ed9-43e0-8b1b-47423e43ea95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kadar-container']</value>
      <webElementGuid>e4d846a3-852c-4feb-b0e5-bab9832829e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perhiasan-form-group']/div[2]/span/span/span/span</value>
      <webElementGuid>03e9413d-1990-4f54-8960-7db561038ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kadar'])[1]/following::span[4]</value>
      <webElementGuid>b7f752ea-6acb-4f42-9fa7-d328e351b761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cincin'])[2]/following::span[6]</value>
      <webElementGuid>34eda292-e3ac-4c05-9627-e5fd833d9cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat Tanpa Mata'])[1]/preceding::span[3]</value>
      <webElementGuid>222a8224-0bf4-4ff7-ab15-f985a629614c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gram'])[1]/preceding::span[3]</value>
      <webElementGuid>399513e2-6644-4b52-9419-78c0e02b776b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>efc04b78-f787-4e03-90ad-c4b98262c71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kadar-container' and @title = 'Pilih Kadar' and (text() = 'Pilih Kadar' or . = 'Pilih Kadar')]</value>
      <webElementGuid>88d34928-752a-43dc-967f-24f68eb27d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
