<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih perhiasan</name>
   <tag></tag>
   <elementGuidId>bc2f8482-f9fb-423e-95b4-74b5eb3a43af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis-perhiasan-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class=&quot;select2-results&quot;]//li[normalize-space()=&quot;Perhiasan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b508859b-d4a1-4b67-9214-5ff10607b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>cb9daa7d-ef9d-421e-ace7-baa85523b9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis-perhiasan-container</value>
      <webElementGuid>a31d2b93-c71b-4627-9fb9-de3f63e1c852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>132f0dd4-ca96-449c-98f4-3bf62e0e8f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69ea5ea1-eac6-47db-9403-2d6fead1a431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Jenis Perhiasan</value>
      <webElementGuid>bd01f974-393c-4bc8-81db-209f73b6de80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenis Perhiasan</value>
      <webElementGuid>657c319c-ddae-4b96-b5b7-b469090016f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis-perhiasan-container&quot;)</value>
      <webElementGuid>8f757f0f-b85d-46e4-a2bb-79208f2bd15a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
