<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_syarat dan ketentuan_checkmark</name>
   <tag></tag>
   <elementGuidId>a28ba2f4-58b2-4669-aeb5-327b1c52241b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModal']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e31b2b2-e11c-465f-a46c-036929cdd397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>17b81fc4-657a-4be9-ac92-542ea52043be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModal&quot;)/div[@class=&quot;modal-content&quot;]/label[@class=&quot;container__checkbox&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>1669697e-de39-4a56-ac98-7fe67cf23d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/label/span</value>
      <webElementGuid>561affae-9c3b-49b4-939f-f344d7a3c1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>34ba9a14-dd54-4697-87b6-9b93047478d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
