<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Jenis Emas</name>
   <tag></tag>
   <elementGuidId>a2835b82-1eda-440b-9d9a-f370a3385aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenis-emas-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis-emas-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>304e2ea2-b4dc-43ce-b419-f77091e5a14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>35601627-b1de-414d-88fe-494553cea43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis-emas-container</value>
      <webElementGuid>35fc6881-fd7f-4319-92a9-7361985f4ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>58822ef0-3f16-4a07-8dfd-58d48d70c7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5711f5de-92ac-47e9-9ed6-a540a1b63e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Jenis Emas</value>
      <webElementGuid>edb3b82c-a11b-46bc-be58-d304256b8a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenis Emas</value>
      <webElementGuid>8020c5b8-a3d5-46d2-8cd8-a76591e24409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis-emas-container&quot;)</value>
      <webElementGuid>00befd4d-e239-4790-bb9e-f426d7004504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis-emas-container']</value>
      <webElementGuid>60efe229-c2c5-4b5f-ac60-f08348809718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mymodaltambahjaminan']/div/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>bd6d3d0f-abc3-4c05-a991-5149aabef30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Emas'])[1]/following::span[4]</value>
      <webElementGuid>08b2b49d-1608-4104-9a98-dd1604c5aac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::span[4]</value>
      <webElementGuid>059b1f17-5c6e-4f0e-8a33-d4c6d4721cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Perhiasan'])[1]/preceding::span[3]</value>
      <webElementGuid>21cbae74-eaa7-4658-8c41-8ee8ae02ed47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jenis Perhiasan'])[2]/preceding::span[3]</value>
      <webElementGuid>5bb7d720-0236-4d7b-a580-2d6f8cdacf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>c5960422-c15a-411c-adf7-247c043bf6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis-emas-container' and @title = 'Pilih Jenis Emas' and (text() = 'Pilih Jenis Emas' or . = 'Pilih Jenis Emas')]</value>
      <webElementGuid>9a9a4e58-a84a-4ab8-bf7b-cd6ab65fed64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
