<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Jenis Perhiasan</name>
   <tag></tag>
   <elementGuidId>16e979c9-24b4-407d-9819-ba3566ac1834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis-perhiasan-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenis-perhiasan-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eec1f030-c9e9-49ea-838e-2bbf1f6baed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9a296b18-72a0-462e-862e-1d956520354e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis-perhiasan-container</value>
      <webElementGuid>e9144bb6-9761-4551-8ea1-91833d53f820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>68d87188-2e20-4f0c-9b52-0f3844440353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>977b76ca-796d-4f8d-8fbc-72cedd4cd769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Jenis Perhiasan</value>
      <webElementGuid>33282706-1b19-4a35-8a89-7a3581ce2c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenis Perhiasan</value>
      <webElementGuid>8a2c2481-8b10-4250-831b-9020f7f92a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis-perhiasan-container&quot;)</value>
      <webElementGuid>e6be4881-d1bf-4a57-981c-eb008b672d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis-perhiasan-container']</value>
      <webElementGuid>ddc55d46-685a-4c25-87c7-e7081d4e8038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perhiasan-form-group']/div/span/span/span/span</value>
      <webElementGuid>da6479c3-b3f4-4748-b117-0d6ef1353a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Perhiasan'])[1]/following::span[4]</value>
      <webElementGuid>fd7bc6f7-2dc2-4719-baf8-a8b56c95e369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhiasan'])[2]/following::span[6]</value>
      <webElementGuid>0ee3dc96-0b00-4ce8-9256-9f11885ba732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kadar'])[1]/preceding::span[3]</value>
      <webElementGuid>bf1ae829-bb2b-44b9-a8e1-b9d50c8914be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kadar'])[2]/preceding::span[3]</value>
      <webElementGuid>f268d034-4b29-440e-8857-387162ae84b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span/span/span/span</value>
      <webElementGuid>76c90ace-f26c-4901-8b64-accc4c700245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis-perhiasan-container' and @title = 'Pilih Jenis Perhiasan' and (text() = 'Pilih Jenis Perhiasan' or . = 'Pilih Jenis Perhiasan')]</value>
      <webElementGuid>c2a317f2-0164-4dd2-a4fe-df5c36a24f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
