<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Kadar</name>
   <tag></tag>
   <elementGuidId>d0000442-b92d-435c-91b1-6f5efe3f56ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-kadar-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-kadar-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a7b2d46-c1c8-496f-837a-97f86e667f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>3fda4713-4364-4c53-a1e7-13a8ff630520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-kadar-container</value>
      <webElementGuid>36103f12-eb1c-4801-a2ee-ac5e8f1d9772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7a7743ce-14ef-4a95-90f4-788cebf0bc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d98514c-1afc-4e0d-8692-347fbe4b314e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Kadar</value>
      <webElementGuid>db5c4f61-b14a-4e20-8b8f-028a0ad7b344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kadar</value>
      <webElementGuid>2f46d051-cd88-4ea2-8fb6-f69193bdb3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-kadar-container&quot;)</value>
      <webElementGuid>4a5a0d5f-ea7d-4479-a30f-834530ecbda9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kadar-container']</value>
      <webElementGuid>9691dc85-f647-48d2-9a65-b2fa4dc2da9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perhiasan-form-group']/div[2]/span/span/span/span</value>
      <webElementGuid>4a01f2ea-49b1-446b-9eab-8e1d8a759574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kadar'])[1]/following::span[4]</value>
      <webElementGuid>577e5fd8-82a2-4b31-ad4e-31e105ce80c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cincin'])[2]/following::span[6]</value>
      <webElementGuid>a93ff06b-df68-49aa-aad9-6c04563133c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat Tanpa Mata'])[1]/preceding::span[3]</value>
      <webElementGuid>3cb0345e-88a4-4391-a395-ca02893f4feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gram'])[1]/preceding::span[3]</value>
      <webElementGuid>730668db-bd57-4418-84d1-e832272adf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>71e7304c-aeff-4f66-9906-57b632a7ce6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kadar-container' and @title = 'Pilih Kadar' and (text() = 'Pilih Kadar' or . = 'Pilih Kadar')]</value>
      <webElementGuid>7ad48c92-be34-4b73-9340-c6acb75da49c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
